add_newline = false

format = """
$username\
$hostname\
$directory\
$golang\
$terraform\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$kubernetes\
$sudo\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$os\
$container\
$shell\
$character"""
command_timeout = 2000

[character]
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'

[username]
disabled = false
style_user = 'bold green'
style_root = 'black bold'
format = '[pol ](bold green)'
show_always = true

[kubernetes]
disabled = true
#⎈ 󰠳 ﴱ
symbol = "󰠳" 
#format = '[[$symbol](blue) [$context](dimmed purple):[$namespace](green)](cyan) '
#format = '[\[[$symbol](blue) [$context](dimmed purple):[$namespace](green)\]](cyan) '
format = '[\([$symbol](blue) [$context](dimmed purple):[$namespace](green)\)](cyan) '

[directory]
style = 'bold blue'
format = '[ﱮ $path]($style)[$read_only]($read_only_style) '
read_only = " "

[git_branch]
# 
symbol = " "
style = 'red'
format = '[$symbol[$branch](red)(:$remote_branch)]($style) '

[git_metrics]
disabled = true
added_style = 'bold blue'
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[git_status]
disabled = false
style = "bg:#394260"
ahead = '[⇡${count}](fg:#EEEDE7)'
behind = '[⇣${count}](fg:#EEEDE7)'
diverged = '[⇡${ahead_count}⇣${behind_count}](fg:#EEEDE7)'
modified = '[ ${count}](blue)'
staged = '[●${count}](yellow)'
stashed = '[⚑${count}](bold purple)'
deleted = '[✖ ${count}](fg:#FF5C5C)'
conflicted = '[✖-${count}](fg:#BF2A2E)'
untracked = '[..${count}](cyan)'
format = '[[($all_status$ahead_behind )](fg:#769ff0)]($style)'

[golang]
disabled = true
symbol = ""
format = '[$symbol $version](bold cyan) '

[terraform]
symbol = "󱁢"
format = '[$symbol $version]($style) '

[memory_usage]
symbol = " "

[os.symbols]
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
CentOS = " "
Debian = " "
Fedora = " "
FreeBSD = " "
Gentoo = " "
Linux = " "
Macos = " "
Manjaro = " "
Mint = " "
openSUSE = " "
OracleLinux = " "
Pop = " "
Raspbian = " "
Redhat = " "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

